import map from './images/map.png'
import { RiDeleteBack2Fill } from 'react-icons/ri'

export const initButtons = [
  { text: '選擇縣市', img: map, className: 'white selectCity' },
  { text: '手動輸入', className: 'manual' },
  { text: '紅', className: '' },
  { text: '藍', className: '' },
  { text: 1, className: 'white' },
  { text: 2, className: 'white' },
  { text: 3, className: 'white' },
  { text: '綠', className: '' },
  { text: '棕', className: '' },
  { text: 4, className: 'white' },
  { text: 5, className: 'white' },
  { text: 6, className: 'white' },
  { text: '橘', className: '' },
  { text: '小', className: '' },
  { text: 7, className: 'white' },
  { text: 8, className: 'white' },
  { text: 9, className: 'white' },
  { text: '幹線', className: '' },
  { text: '更多', className: '' },
  { text: 'c', className: '' },
  { text: 0, className: 'white' },
  { text: <RiDeleteBack2Fill />, className: '' },
]
export const selectCityButtons = [
  { text: '台北市', className: '' },
  { text: '新北市', className: '' },
  { text: '基隆市', className: '' },
  { text: '桃園市', className: '' },
  { text: '新竹市', className: '' },
  { text: '新竹縣', className: '' },
  { text: '苗栗縣', className: '' },
  { text: '台中市', className: '' },
  { text: '南投縣', className: '' },
  { text: '彰化縣', className: '' },
  { text: '雲林縣', className: '' },
  { text: '嘉義市', className: '' },
  { text: '嘉義縣', className: '' },
  { text: '台南市', className: '' },
  { text: '高雄市', className: '' },
  { text: '屏東縣', className: '' },
  { text: '台東縣', className: '' },
  { text: '花蓮縣', className: '' },
  { text: '宜蘭縣', className: '' },
  { text: '澎湖縣', className: '' },
  { text: '金門縣', className: '' },
  { text: '連江縣', className: '' },
  { text: '設定', className: 'set' },
]
export const moreButtons = [
  { text: 'F', className: '' },
  { text: 'R', className: '' },
  { text: 'T', className: '' },
  { text: '快', className: '' },
  { text: '內科', className: '' },
  { text: '跳蛙', className: '' },
  { text: '通勤', className: '' },
  { text: '南軟', className: '' },
  { text: '先導', className: '' },
  { text: '夜間', className: '' },
  { text: '市民', className: '' },
  { text: '其他', className: '' },
  { text: '回上一頁', className: 'set' },
]
